version: "3"
services:
  redis:
    image: redis:alpine
    container_name: redis

  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    container_name: postgres_db

  app:
    build: .
    volumes:
      - .:/django
    ports:
      - 8000:8000
    image: app:django
    container_name: django_app
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db

  celery:
    restart: always
    build:
      context: .
    command: celery -A config worker -l INFO
    volumes:
      - .:/django
    container_name: celery
    depends_on:
      - db
      - redis
      - app

  celery_beat:
    restart: always
    build:
      context: .
    command: celery -A config beat -l INFO --scheduler django_celery_beat.schedulers:DatabaseScheduler
    volumes:
      - .:/django
    container_name: celery_beat
    depends_on:
      - db
      - redis
      - celery
      - app
