# Generated by Django 4.1 on 2023-05-15 19:11

import core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='آخرین به روز رسانی')),
                ('is_deleted', models.BooleanField(default=False)),
                ('delete_date', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ حذف شدن')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='ایمیل')),
                ('phone', models.CharField(max_length=11, verbose_name='شماره تلفن')),
                ('first_name', models.CharField(max_length=64, verbose_name='نام')),
                ('last_name', models.CharField(max_length=64, verbose_name='نام خانوادگی')),
                ('is_active', models.BooleanField(default=False, verbose_name='فعال')),
                ('is_staff', models.BooleanField(default=False, verbose_name='کارمند')),
                ('role', models.CharField(choices=[('a', 'ادمین'), ('o', 'ناظر'), ('c', 'مشتری')], max_length=1, verbose_name='نقش کاربر')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to=core.models.user_image_file_path, verbose_name='تصویر پروفایل')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='آخرین به روز رسانی')),
                ('is_deleted', models.BooleanField(default=False)),
                ('delete_date', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ حذف شدن')),
                ('country', models.CharField(max_length=32, verbose_name='کشور')),
                ('province', models.CharField(max_length=32, verbose_name='استان')),
                ('city', models.CharField(max_length=32, verbose_name='شهر')),
                ('street', models.CharField(max_length=32, verbose_name='خیابان')),
                ('zip_code', models.CharField(max_length=10, verbose_name='کد پستی')),
                ('pelak', models.CharField(max_length=4, verbose_name='پلاک')),
                ('full_address', models.TextField(max_length=512, verbose_name='آدرس کامل')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
