# Generated by Django 4.1 on 2023-05-16 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='single_use',
            field=models.BooleanField(default=True, verbose_name='یکبار مصرف'),
        ),
    ]
