# Generated by Django 4.1 on 2023-05-16 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_discount_single_use'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='description',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='meta_description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='توضیح کوتاه (SEO)'),
        ),
    ]
