# Generated by Django 4.1 on 2023-05-21 14:48

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, default='<function user_image_file_path at 0x7fbe3f06c670>/no_image.png', null=True, upload_to=core.models.user_image_file_path, verbose_name='تصویر پروفایل'),
        ),
    ]
