# Generated by Django 4.1 on 2023-05-21 18:27

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_user_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, default='uploads/user/no_image.png', null=True, upload_to=core.models.user_image_file_path, verbose_name='تصویر پروفایل'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('a', 'ادمین'), ('o', 'ناظر'), ('c', 'مشتری')], default='c', max_length=1, verbose_name='نقش کاربر'),
        ),
    ]
