# Generated by Django 4.1 on 2023-05-31 22:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator('^09\\d{9}', code='invalid_phone', message='تلفن نا معتبر')], verbose_name='شماره تلفن'),
        ),
    ]
