# Generated by Django 4.1 on 2023-05-16 08:01

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import shop.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_alter_discount_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='آخرین به روز رسانی')),
                ('is_deleted', models.BooleanField(default=False)),
                ('delete_date', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ حذف شدن')),
                ('title', models.CharField(max_length=64, verbose_name='عنوان دسته')),
                ('meta_title', models.CharField(blank=True, max_length=64, null=True, verbose_name='عنوان دسته(SEO)')),
                ('meta_description', models.CharField(blank=True, max_length=255, null=True, verbose_name='توضیح کوتاه')),
                ('description', models.TextField(blank=True, max_length=1000, null=True)),
                ('show_in_menu', models.BooleanField(default=False)),
                ('discount', models.ManyToManyField(related_name='category_discount_related_name', to='core.discount')),
                ('parent_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.category')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='آخرین به روز رسانی')),
                ('is_deleted', models.BooleanField(default=False)),
                ('delete_date', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ حذف شدن')),
                ('name', models.CharField(max_length=255, verbose_name='نام محصول')),
                ('brand', models.CharField(max_length=128, verbose_name='سازنده')),
                ('price', models.PositiveIntegerField(verbose_name='قیمت')),
                ('quantity', models.PositiveIntegerField(verbose_name='تعداد موجودی')),
                ('tax', models.FloatField(default=9, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='درصد مالیات')),
                ('slug', models.SlugField()),
                ('meta_description', models.CharField(max_length=255, verbose_name='توضیح کوتاه')),
                ('description', models.TextField(max_length=5000, verbose_name='توضیح کامل')),
                ('extra_data', models.JSONField(verbose_name='مشخصات اضافه')),
                ('category', models.ManyToManyField(related_name='product_category_related_name', to='shop.category')),
                ('discount', models.ManyToManyField(related_name='product_discount_related_name', to='core.discount')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WishList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='آخرین به روز رسانی')),
                ('is_deleted', models.BooleanField(default=False)),
                ('delete_date', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ حذف شدن')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='آخرین به روز رسانی')),
                ('is_deleted', models.BooleanField(default=False)),
                ('delete_date', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ حذف شدن')),
                ('name', models.CharField(max_length=32, verbose_name='تگ')),
                ('slug', models.SlugField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_product_related_name', to='shop.product')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='آخرین به روز رسانی')),
                ('is_deleted', models.BooleanField(default=False)),
                ('delete_date', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ حذف شدن')),
                ('image', models.FileField(upload_to=shop.models.post_image_file_path, verbose_name='تصویر')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='product',
            name='tag',
            field=models.ManyToManyField(related_name='product_category_related_name', to='shop.tag'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='آخرین به روز رسانی')),
                ('is_deleted', models.BooleanField(default=False)),
                ('delete_date', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ حذف شدن')),
                ('title', models.CharField(max_length=150, verbose_name='عنوان نظر')),
                ('content', models.TextField(max_length=500, verbose_name='متن نظر')),
                ('rating', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='امتیاز')),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product')),
                ('parent_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.comment')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
