# Generated by Django 4.1 on 2023-05-16 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_remove_tag_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='extra_data',
            field=models.JSONField(null=True, verbose_name='مشخصات اضافه(JSON)'),
        ),
    ]
