# Generated by Django 4.1 on 2023-05-16 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_discount_description_and_more'),
        ('shop', '0003_alter_product_extra_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='discount',
            field=models.ManyToManyField(blank=True, null=True, related_name='category_discount_related_name', to='core.discount'),
        ),
        migrations.AlterField(
            model_name='category',
            name='parent_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.ManyToManyField(blank=True, null=True, related_name='product_discount_related_name', to='core.discount'),
        ),
    ]
