# Generated by Django 4.1 on 2023-05-16 09:26

from django.db import migrations, models
import shop.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_alter_category_options_alter_comment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='thumbnail',
            field=models.ImageField(default=1, upload_to=shop.models.post_image_file_path),
            preserve_default=False,
        ),
    ]
