# Generated by Django 4.1 on 2023-05-16 12:32

from django.db import migrations, models
import shop.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_product_thumbnail'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimage',
            options={'verbose_name': 'تصویر محصول', 'verbose_name_plural': 'تصویر های گالری محصول'},
        ),
        migrations.AlterField(
            model_name='product',
            name='thumbnail',
            field=models.ImageField(upload_to=shop.models.post_image_file_path, verbose_name='تصویر اصلی'),
        ),
    ]
