# Generated by Django 4.1 on 2023-05-16 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_alter_productimage_options_alter_product_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='extra_data',
            field=models.JSONField(blank=True, null=True, verbose_name='مشخصات اضافه(JSON)'),
        ),
    ]
