# Generated by Django 4.1 on 2023-05-16 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_alter_product_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='MagicSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='آخرین به روز رسانی')),
                ('is_deleted', models.BooleanField(default=False)),
                ('delete_date', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ حذف شدن')),
                ('name', models.CharField(max_length=255, verbose_name='نام')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='نام منحصر به فرد')),
                ('start_date', models.DateTimeField(verbose_name='تاریخ شروع')),
                ('end_date', models.DateTimeField(verbose_name='تاریخ پایان')),
            ],
            options={
                'verbose_name': 'حراج شگفت انگیز',
                'verbose_name_plural': 'حراج های شگفت انگیز',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='magic_sale',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shop.magicsale'),
            preserve_default=False,
        ),
    ]
