# Generated by Django 4.1 on 2023-05-18 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_user_first_name_alter_user_last_name_and_more'),
        ('shop', '0013_magicsale_product_magic_sale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(related_name='product_category_related_name', to='shop.category', verbose_name='دسته بندی'),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.ManyToManyField(blank=True, null=True, related_name='product_discount_related_name', to='core.discount', verbose_name='تخفیف'),
        ),
        migrations.AlterField(
            model_name='product',
            name='magic_sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.magicsale', verbose_name='حراج شگفت انگیز'),
        ),
    ]
