# Generated by Django 4.1 on 2023-05-18 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_alter_product_category_alter_product_discount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='magic_sale',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.magicsale', verbose_name='حراج شگفت انگیز'),
        ),
    ]
