# Generated by Django 4.1 on 2023-05-20 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_alter_product_magic_sale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='magic_sale',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.magicsale', verbose_name='حراج شگفت انگیز'),
        ),
    ]
