# Generated by Django 4.1 on 2023-05-21 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_alter_product_magic_sale'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='title',
        ),
    ]
