# Generated by Django 4.1 on 2023-06-12 20:36

import core.models_on_delete
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_alter_comment_parent_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='parent_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=core.models_on_delete.SOFT_CASCADE, related_name='related_name', to='shop.comment'),
        ),
    ]
