# Generated by Django 4.1 on 2023-05-16 14:09

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0012_alter_product_description'),
        ('core', '0003_alter_discount_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='آخرین به روز رسانی')),
                ('is_deleted', models.BooleanField(default=False)),
                ('delete_date', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ حذف شدن')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='آخرین به روز رسانی')),
                ('is_deleted', models.BooleanField(default=False)),
                ('delete_date', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ حذف شدن')),
                ('status', models.CharField(choices=[('1', 'در انتظار پرداخت'), ('2', 'پرداخت موفق'), ('3', 'پرداخت ناموفق'), ('4', 'انصراف'), ('5', 'منقضی شده'), ('6', 'آماده ارسال'), ('7', 'ارسال شده'), ('8', 'تحویل شده')], max_length=1, verbose_name='وضعیت')),
                ('shipping', models.CharField(choices=[('1', 'ارسال پست عادی'), ('2', 'ارسال پست سفارشی'), ('3', 'ارسال پست پیشتاز'), ('4', 'ارسال تیپاکس'), ('5', 'ارسال ترمینال'), ('6', 'ارسال پیک')], max_length=1, verbose_name='روش ارسال')),
                ('time_for_pay', models.DateTimeField(default=datetime.datetime(2023, 5, 16, 14, 39, 54, 188745, tzinfo=datetime.timezone.utc), verbose_name='زمال پرداخت')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.address')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='آخرین به روز رسانی')),
                ('is_deleted', models.BooleanField(default=False)),
                ('delete_date', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ حذف شدن')),
                ('status', models.CharField(choices=[('1', 'در انتظار'), ('2', 'موفق'), ('3', 'نا موفق')], max_length=1, verbose_name='وضعیت')),
                ('total_price', models.PositiveIntegerField(verbose_name='قیمت کل')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='آخرین به روز رسانی')),
                ('is_deleted', models.BooleanField(default=False)),
                ('delete_date', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ حذف شدن')),
                ('count', models.PositiveIntegerField(verbose_name='تعداد')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='آخرین به روز رسانی')),
                ('is_deleted', models.BooleanField(default=False)),
                ('delete_date', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ حذف شدن')),
                ('count', models.PositiveIntegerField(verbose_name='تعداد')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.cart')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
