# Generated by Django 4.1 on 2023-05-16 14:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'verbose_name': 'تراکنش', 'verbose_name_plural': 'تراکنش ها'},
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_code',
            field=models.CharField(default=1, max_length=64, verbose_name='کد تراکنش'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='time_for_pay',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 16, 14, 50, 53, 894556, tzinfo=datetime.timezone.utc), verbose_name='زمال پرداخت'),
        ),
    ]
