# Generated by Django 4.1 on 2023-05-16 15:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_cart_options_alter_cartitem_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='time_for_pay',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 16, 16, 25, 24, 416092, tzinfo=datetime.timezone.utc), verbose_name='زمال پرداخت'),
        ),
    ]
