# Generated by Django 4.1 on 2023-05-18 19:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_alter_order_time_for_pay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('1', 'در انتظار پرداخت'), ('2', 'پرداخت موفق'), ('3', 'پرداخت ناموفق'), ('4', 'انصراف'), ('5', 'منقضی شده'), ('6', 'آماده ارسال'), ('7', 'ارسال شده'), ('8', 'تحویل شده')], default='1', max_length=1, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='order',
            name='time_for_pay',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 18, 19, 58, 17, 466190, tzinfo=datetime.timezone.utc), verbose_name='زمال پرداخت'),
        ),
    ]
