# Generated by Django 4.1 on 2023-05-19 09:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_alter_order_status_alter_order_time_for_pay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='time_for_pay',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 19, 10, 29, 32, 968768, tzinfo=datetime.timezone.utc), verbose_name='زمال پرداخت'),
        ),
    ]
