# Generated by Django 4.1 on 2023-05-25 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0017_alter_order_time_for_pay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='time_for_pay',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمال مجاز برای پرداخت'),
        ),
    ]
