# Generated by Django 4.1 on 2023-05-25 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0018_alter_order_time_for_pay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shipping',
            field=models.CharField(choices=[('1', 'ارسال پست عادی'), ('2', 'ارسال پست سفارشی'), ('3', 'ارسال پست پیشتاز'), ('4', 'ارسال تیپاکس'), ('5', 'ارسال ترمینال'), ('6', 'ارسال پیک')], default='1', max_length=1, verbose_name='روش ارسال'),
        ),
    ]
